apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-worker-transfer-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  POD_NAME: "go-transfer-credit"
  API_VERSION: "2.1"
  #DB_HOST: "db-arch.couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  SETPOD_AZ: "false"
  KAFKA_USER: "admin"
  KAFKA_PASSWORD: "admin"
  KAFKA_PROTOCOL: "SASL_SSL"
  KAFKA_MECHANISM: "SCRAM-SHA-512"
  KAFKA_CLIENT_ID: "GO-WORKER-TRANSFER"
  KAFKA_GROUP_ID: "GROUP-WORKER-TRANSFER-01"
  KAFKA_BROKER_1: "b-1.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_BROKER_2: "b-2.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_BROKER_3: "b-3.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_PARTITION: "3"
  KAFKA_REPLICATION: "2"
  #SERVER_URL_DOMAIN: "http://svc-go-credit.test-a.svc.cluster.local:5001"
  SERVICE_URL_DOMAIN: "https://vpce.global.dev.caradhras.io/pv"
  X_APIGW_API_ID: "cy5ry2263h"
  TOPIC_CREDIT: "topic.credit.01"
  TOPIC_DEBIT: "topic.debit.01"
  TOPIC_TRANSFER: "topic.transfer.01"
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-02-xray-collector.default.svc.cluster.local:4317"