apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app-name go-worker-transfer
  namespace: test-a
  labels:
    app: *app-name
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: *app-name
  template:
    metadata:
      labels:
        app: *app-name
    spec:
      volumes:
      - name: volume-secret
        secret:
          secretName: es-rds-arch-secret-go-worker-transfer
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 3000
      containers:
      - name: *app-name
        image: 908671954593.dkr.ecr.us-east-2.amazonaws.com/go-worker-transfer:latest
        env:
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: xray-service.amazon-cloudwatch:2000
        envFrom:
        - configMapRef:
            name: go-worker-transfer-cm
        volumeMounts:
          - mountPath: "/var/pod/secret"
            name: volume-secret
            readOnly: true
        resources:
           requests:
             cpu: 10m
             memory: 50Mi
           limits:
             cpu: 100m
             memory: 100Mi
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 1100
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "ps -A | grep go-worker-transfer | grep -v grep"
            initialDelaySeconds: 3
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
                labelSelector:
                  matchLabels:
                    app: *app-name
              weight: 100
